# Generated by Django 4.1.4 on 2023-03-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_neighbourhood_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaporEkle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapor_no', models.CharField(max_length=255, null=True, verbose_name='Rapor Numarası')),
                ('ada', models.BigIntegerField(null=True, verbose_name='Ada')),
                ('parsel', models.BigIntegerField(null=True, verbose_name='Parsel')),
                ('enlem', models.FloatField(null=True, verbose_name='Enlem')),
                ('boylam', models.FloatField(null=True, verbose_name='Boylam')),
                ('ana_tasinmaz_nitelik', models.CharField(max_length=500, null=True, verbose_name='Ana Taşınmaz Nitelik')),
                ('nitelik', models.CharField(max_length=500, null=True, verbose_name='Nitelik')),
                ('yuzolcum', models.FloatField(null=True, verbose_name='Yüzölçüm')),
                ('kat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kat')),
                ('oda_sayisi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Oda Sayısı')),
                ('isinma_sistemi', models.CharField(choices=[('1', 'MERKEZİ SİSTEM'), ('2', 'KOMBİ'), ('3', 'SOBA'), ('4', 'YOK'), ('6', 'DİĞER')], max_length=255, null=True, verbose_name='Isınma Sistemi')),
                ('deger_tarihi', models.DateField(null=True, verbose_name='Değerleme Tarihi')),
                ('asansor', models.CharField(choices=[('1', 'VAR'), ('2', 'YOK')], max_length=255, null=True, verbose_name='Asansör')),
                ('otopark', models.CharField(choices=[('1', 'VAR'), ('2', 'YOK')], max_length=255, null=True, verbose_name='Otopark')),
                ('guvenlik', models.CharField(choices=[('1', 'VAR'), ('2', 'YOK')], max_length=255, null=True, verbose_name='Güvenlik')),
                ('yapi_kalitesi', models.CharField(choices=[('1', 'LÜKS'), ('2', 'İYİ'), ('3', 'ORTA'), ('4', 'DÜŞÜK'), ('5', 'YAPI YOK')], max_length=255, null=True, verbose_name='Yapı Kalitesi')),
                ('yapim_yili', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Yapım Yılı')),
                ('dosya_konumu', models.CharField(max_length=500, null=True, verbose_name='Dosya Konumu')),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.citys', verbose_name='İl')),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.county', verbose_name='İlçe')),
                ('mahalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.neighbourhood', verbose_name='Mahalle')),
            ],
            options={
                'verbose_name': 'Eklenen Raporlar',
                'verbose_name_plural': 'Eklenen Raporlar',
            },
        ),
    ]
