# Generated by Django 4.1.4 on 2023-03-17 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expert_info', '0002_raporekle_created_at_raporekle_is_exist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raporekle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
