# Generated by Django 4.1.4 on 2023-03-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_info', '0003_raporekle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='raporekle',
            name='deger',
            field=models.FloatField(null=True, verbose_name='Değer'),
        ),
    ]
