# Generated by Django 4.1.4 on 2023-03-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_info', '0005_prim_maas_arackira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prim',
            name='kira',
        ),
        migrations.AddField(
            model_name='prim',
            name='prim',
            field=models.FloatField(null=True, verbose_name='Rapor Ücreti'),
        ),
    ]
