# Generated by Django 4.1.4 on 2023-03-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_info', '0006_remove_prim_kira_prim_prim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prim',
            name='prim',
            field=models.FloatField(blank=True, null=True, verbose_name='Rapor Ücreti'),
        ),
        migrations.AlterField(
            model_name='prim',
            name='rapor_no',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Rapor Numarası'),
        ),
    ]
