# Generated by Django 4.1.4 on 2023-03-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_info', '0008_alter_prim_yil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arackira',
            name='yil',
            field=models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034')], max_length=50, null=True, verbose_name='Yıl'),
        ),
        migrations.AlterField(
            model_name='maas',
            name='yil',
            field=models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034')], max_length=50, null=True, verbose_name='Yıl'),
        ),
    ]
