# Generated by Django 4.1.4 on 2023-03-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_info', '0010_yapimaliyetleri'),
    ]

    operations = [
        migrations.AddField(
            model_name='yapimaliyetleri',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='yapimaliyetleri',
            name='is_exist',
            field=models.BooleanField(default=True, null=True, verbose_name='Mevcut mu?'),
        ),
        migrations.AddField(
            model_name='yapimaliyetleri',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
