# Generated by Django 4.1.4 on 2023-03-19 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_neighbourhood_county'),
        ('expert_info', '0011_yapimaliyetleri_created_at_yapimaliyetleri_is_exist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImarPlanOnaylari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ada', models.BigIntegerField(null=True, verbose_name='Ada')),
                ('parsel', models.BigIntegerField(null=True, verbose_name='Parsel')),
                ('tarih', models.DateField(null=True, verbose_name='Onay Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_exist', models.BooleanField(default=True, null=True, verbose_name='Mevcut mu?')),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.citys', verbose_name='İl')),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.county', verbose_name='İlçe')),
                ('mahalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.neighbourhood', verbose_name='Mahalle')),
            ],
            options={
                'verbose_name': 'İmar Planı Onay Tarihleri',
                'verbose_name_plural': 'İmar Planı Onay Tarihleri',
            },
        ),
    ]
