# Generated by Django 4.1.4 on 2023-03-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_citys_created_at_citys_is_active_citys_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.county'),
        ),
    ]
